logging:
  file:
    enable: true
    level: INFO
    path: logs
    rotation: "10 MB"
    retention: "7 days"
  console:
    enable: true
    level: INFO

db_meta:
  host: 152.136.228.231
  port: 3306
  user: atguigu
  password: Atguigu.123
  database: meta

db_dw:
  host: 152.136.228.231
  port: 3306
  user: atguigu
  password: Atguigu.123
  database: dw

qdrant:
  host: 152.136.228.231
  port: 6333
  embedding_size: 1024

embedding:
  host: 152.136.228.231
  port: 8081
  # 本地 BGE-M3 模型路径
  model: /Users/a123/D盘/学习/尚硅谷/bge-large-zh-v1.5


es:
  # 腾讯云 Elasticsearch Service 公网访问地址
  host: es-jqd93oyw.public.tencentelasticsearch.com
  port: 9200
  index_name: data_agent
  scheme: https
  user: elastic                        # 你的用户名
  password: Swdwlsnyt920.              # 你的密码
  verify_certs: true                   # https 模式，腾讯云证书默认受信任
  ca_certs:                            # 留空


llm:
  model_name: deepseek-v4-pro
  api_key: <deepseek_api_key>
